### ISSUE TITLE
Set IIM42652 full scale range

### ISSUE THREAD

**Issue by m-nahirny** [RAKWireless/RAK12033-IIM42652#1]
The value for the full scale range is not set correctly since the bits are not shifted to the top 3 bits. The function set_accel_fsr should be modified to:

void IIM42652::set_accel_fsr(IIM42652_ACCEL_CONFIG0_FS_SEL_t accel_fsr_g)
{
  uint8_t accel_cfg_0_reg;

  readRegister(IIM42652_REG_ACCEL_CONFIG0, &accel_cfg_0_reg, 1);

  accel_cfg_0_reg &= (uint8_t)~BIT_ACCEL_CONFIG0_FS_SEL_MASK;
  accel_cfg_0_reg |= (uint8_t)accel_fsr_g << BIT_ACCEL_CONFIG0_FS_SEL_POS;

  writeRegister(IIM42652_REG_ACCEL_CONFIG0, &accel_cfg_0_reg, 1);
}

**Comment by beegee-tokyo** [comment]
Fixed in V1.0.1.
Thank you @m-nahirny for reporting the problem.
